In [35]:
# Jai shree RAM

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('spam.csv', encoding="ISO-8859-1")

In [3]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
# basic operations

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [6]:
df.describe()

v1                      v2  \
count   5572                    5572   
unique     2                    5169   
top      ham  Sorry, I'll call later   
freq    4825                      30   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2

In [7]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [8]:
# df[df.duplicated()]

In [9]:
df.sample()

v1                                                 v2 Unnamed: 2  \
2993  ham  No idea, I guess we'll work that out an hour a...        NaN   

     Unnamed: 3 Unnamed: 4  
2993        NaN        NaN

In [10]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis = 1, inplace = True)

In [11]:
df.sample()

v1                                                 v2
673  ham  Ditto. And you won't have to worry about me sa...

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
label_encode = LabelEncoder()

In [14]:
# first renaming columns name

df.rename(columns={'v1':'target', 'v2':'text'}, inplace = True)

In [15]:
df.sample()

target                                               text
4371   spam  Ur balance is now å£600. Next question: Comple...

In [16]:
df['target'] = label_encode.fit_transform(df['target'])

In [185]:
df.iloc[5140]

target                                  0
text                Yeah it's jus rite...
text_len                               21
words_len                               6
sen_len                                 1
transformed_text             yeah ju rite
Name: 5541, dtype: object

In [17]:
df.sample()

target                                               text
5140       0  Yeah I imagine he would be really gentle. Unli...

In [18]:
df.isnull().sum()

target    0
text      0
dtype: int64

In [19]:
df.duplicated().sum()

403

In [20]:
df = df.drop_duplicates(keep = 'first')

In [21]:
df.sample()

target                      text
1813       0  Yes we are chatting too.

In [22]:
df.duplicated().sum()

0

In [23]:
df.shape

(5169, 2)

## EDA

In [24]:
df['target'].value_counts()

target
0    4516
1     653
Name: count, dtype: int64

In [25]:
# data seems imbalanced

In [30]:
# now dealing with text data

In [33]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [32]:
# nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nancy\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [64]:
# nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nancy\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [79]:
# nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nancy\AppData\Roaming\nltk_data...


True

In [34]:
df.sample()

target                                               text
4114       0  Sorry. You never hear unless you book it. One ...

In [36]:
df['text_len'] = df['text'].apply(lambda x : len(x))

In [38]:
df.head()

target                                               text  text_len
0       0  Go until jurong point, crazy.. Available only ...       111
1       0                      Ok lar... Joking wif u oni...        29
2       1  Free entry in 2 a wkly comp to win FA Cup fina...       155
3       0  U dun say so early hor... U c already then say...        49
4       0  Nah I don't think he goes to usf, he lives aro...        61

In [40]:
df['words_len'] = df['text'].apply(lambda x : len(nltk.word_tokenize(x)))

In [41]:
df.head()

target                                               text  text_len  \
0       0  Go until jurong point, crazy.. Available only ...       111   
1       0                      Ok lar... Joking wif u oni...        29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...       155   
3       0  U dun say so early hor... U c already then say...        49   
4       0  Nah I don't think he goes to usf, he lives aro...        61   

   words_len  
0         24  
1          8  
2         37  
3         13  
4         15

In [44]:
df['sen_len'] = df['text'].apply(lambda x:len(nltk.sent_tokenize(x)))

In [45]:
df.head()

target                                               text  text_len  \
0       0  Go until jurong point, crazy.. Available only ...       111   
1       0                      Ok lar... Joking wif u oni...        29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...       155   
3       0  U dun say so early hor... U c already then say...        49   
4       0  Nah I don't think he goes to usf, he lives aro...        61   

   words_len  sen_len  
0         24        2  
1          8        2  
2         37        2  
3         13        1  
4         15        1

## Data Preprocessing
- Lower case
- Tokenization
- Removing special characters
- Removing stop words and punctuation
- Stemming

In [73]:
import string
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [223]:
def transform_text(text):
    # lower casing
    text = text.lower()
    
    # coverting text into list of words
    text = nltk.word_tokenize(text)
    
    y = []
    
    # removing special characters
    for i in text:
        if i.isalnum():
            y.append(i)
    
    text = y[:]
    y.clear()
    
    # removing stopwords/helping words
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
            
    text = y[:]
    y.clear()
    
    # Normalization of word i.e converting words into their base form.
    for i in text:
        y.append(ps.stem(i))
    
    return " ".join(y)

In [224]:
transform_text('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore')

'go jurong point crazi avail bugi n great world la e buffet cine got amor'

In [97]:
# Transforming text 

df['transformed_text'] = df['text'].apply(transform_text)

In [98]:
%%time

df.head()

CPU times: total: 0 ns
Wall time: 0 ns


target                                               text  text_len  \
0       0  Go until jurong point, crazy.. Available only ...       111   
1       0                      Ok lar... Joking wif u oni...        29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...       155   
3       0  U dun say so early hor... U c already then say...        49   
4       0  Nah I don't think he goes to usf, he lives aro...        61   

   words_len  sen_len                                   transformed_text  
0         24        2  go jurong point crazi avail bugi n great world...  
1          8        2                              ok lar joke wif u oni  
2         37        2  free entri 2 wkli comp win fa cup final tkt 21...  
3         13        1                u dun say earli hor u c alreadi say  
4         15        1               nah think goe usf live around though

## Model building 

In [189]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

In [190]:
# using countvectorizer i.e bag of words

In [191]:
# X = cv.fit_transform(df['transformed_text']).toarray()
X = tfidf.fit_transform(df['transformed_text']).toarray()

In [192]:
X.shape

(5169, 3000)

In [193]:
y = df['target']

In [194]:
from sklearn.model_selection import train_test_split

In [195]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=2, test_size=0.2)

In [196]:
X_train.shape

(4135, 3000)

In [197]:
X_train[1]

array([0., 0., 0., ..., 0., 0., 0.])

In [198]:
X_test.shape

(1034, 3000)

In [199]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score

In [200]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [201]:
model_list = [gnb, mnb, bnb]

In [202]:
for i in model_list:
    
    i.fit(X_train, y_train)
    y_pred = i.predict(X_test)
    
    print(str(i)[:-2])
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(precision_score(y_test,y_pred), '\n')

GaussianNB
0.8694390715667312
[[788 108]
 [ 27 111]]
0.5068493150684932 

MultinomialNB
0.9709864603481625
[[896   0]
 [ 30 108]]
1.0 

BernoulliNB
0.9835589941972921
[[895   1]
 [ 16 122]]
0.991869918699187 



In [203]:
# with tfidf - MNB - best

In [204]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [205]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)

In [206]:
clfs = {
    'SVC' : svc,
    'KN' : knc, 
    'NB': mnb, 
    'DT': dtc, 
    'LR': lrc, 
    'RF': rfc, 
    'AdaBoost': abc, 
    'GBDT':gbdt
}

In [207]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    
    return accuracy,precision

In [208]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision = train_classifier(clf, X_train,y_train,X_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  SVC
Accuracy -  0.9758220502901354
Precision -  0.9747899159663865
For  KN
Accuracy -  0.9052224371373307
Precision -  1.0
For  NB
Accuracy -  0.9709864603481625
Precision -  1.0
For  DT
Accuracy -  0.9274661508704062
Precision -  0.8118811881188119
For  LR
Accuracy -  0.9584139264990329
Precision -  0.9702970297029703
For  RF
Accuracy -  0.9758220502901354
Precision -  0.9829059829059829
For  AdaBoost
Accuracy -  0.960348162475822
Precision -  0.9292035398230089
For  GBDT
Accuracy -  0.9468085106382979
Precision -  0.9191919191919192


In [209]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)

In [210]:
performance_df

Algorithm  Accuracy  Precision
1        KN  0.905222   1.000000
2        NB  0.970986   1.000000
5        RF  0.975822   0.982906
0       SVC  0.975822   0.974790
4        LR  0.958414   0.970297
6  AdaBoost  0.960348   0.929204
7      GBDT  0.946809   0.919192
3        DT  0.927466   0.811881

In [187]:
# In above table we have 3 models performing pretty well, KNC, MNB and RFC

In [211]:
# lets change some parameters and then check the performance
# after changing parameters we have following models doing well, MNB, KNC and RFC

In [212]:
# out of all these we have multinominal naive bayes model out-performing others

In [213]:
# so we will choose MNB model

In [214]:
import pickle

pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(mnb,open('model.pkl','wb'))